name: Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Deploying frontend..."

            cd /var/www/brewnest-frontend
            git pull origin main

            cd /var/www
            docker-compose up -d --build frontend

            echo "Frontend deployed"
